name: Arduino Clang Static Analysis

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  clang-analysis:
    runs-on: ubuntu-22.04 #ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install LLVM tools with scan-build
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg lsb-release
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 14
        
    - name: Install scan-build
      run: |
       sudo apt-get update
       sudo apt-get install -y clang-tools
    
    - name: Prepare Arduino .ino file for analysis
      run: |
        cp Lab1/*.ino Lab1/temp.cpp
        echo '#include <Arduino.h>' | cat - Lab1/temp.cpp > Lab1/analyzable.cpp

    - name: Run scan-build with clang++-14
      run: |
        mkdir -p analysis-report
        scan-build -o analysis-report clang++-14 -c Lab1/analyzable.cpp -I/usr/share/arduino/hardware/arduino/cores/arduino || true

    - name: Upload analysis report
      uses: actions/upload-artifact@v4
      with:
        name: clang-static-analysis
        path: analysis-report
