name: Arduino Clang Static Analysis

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  clang-analysis:
    runs-on: ubuntu-22.04 #ubuntu-latest
    
   steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install clang-tools (scan-build)
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tools

      - name: Install arduino-cli
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin

      - name: Set up Arduino CLI core
        run: |
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Run static analysis with scan-build
        run: |
          mkdir -p analysis-report
          scan-build -o analysis-report --use-cc=clang --use-c++=clang++ arduino-cli compile --fqbn arduino:avr:mega Lab1


    - name: Upload analysis report
      uses: actions/upload-artifact@v4
      with:
        name: clang-static-analysis
        path: analysis-report
